[default_session]
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "Home"
path = "~/"
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "Obsidian"
path = "~/github/Obsidian"
startup_command = "nvim ."
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "ghostty config"
path = "~/.config/ghostty"
startup_command = "nvim config"

[[session]]
name = "tmux config"
path = "~/.config/tmux"
startup_command = "nvim tmux.conf"
preview_command = "bat --color=always ~/.config/tmux/tmux.conf"

[[session]]
name = "sesh config"
path = "~/.config/sesh"
startup_command = "nvim sesh.toml"
preview_command = "bat --color=always ~/.config/sesh/sesh.toml"

[[session]]
name = "zshrc"
path = "~/.config/zshrc"
startup_command = "nvim ."
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "nvim config"
path = "~/.config/nvim"
startup_command = "nvim ."
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "tmuxinator config"
path = "~/.config/tmuxinator"
startup_command = "nvim ."
preview_command = "eza --all --git --icons --color=always {}"
