# Execute your favorite apps at launch
exec-once = logid -c ~/.config/logiops/logid.cfg;
exec-once = systemctl disable --now logid;
exec-once = systemctl enable --now logid;
exec-once = /usr/bin/pypr --debug /tmp/pypr.log
exec-once = hyprpaper
exec-once = swaync # Notifications
exec-once = kanshi -c ~/.config/kanshi/configLMR # Monitor config
exec-once = systemctl --user start hyprpolkitagent
exec-once = wl-paste --type text --watch cliphist store # Stores only text data
exec-once = wl-paste --type image --watch cliphist store # Stores only image data
exec-once = systemctl start tailscaled
exec-once = powerprofilesctl set performance
exec-once = hyprpm reload -n
